name: hotel_booking
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  get_it: ^8.0.0
  hive: ^2.2.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.19.0
  http: ^1.2.2
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true